version: '3.8'

services:
  backend:
    build: .
    ports:
      - "80:8000"
    volumes:
      - .:/app
    command: >
      sh -c "python manage.py migrate &&
          python manage.py runserver 0.0.0.0:8000"
